name: Update html

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
    - name: Step2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Step 3 - Build package Maven
      run: |
        mvn -B package --file pom.xml
    - name: Step4 - Test
      run: mvn test
