name: test

on:
  push:
    branches:
      - master
jobs:
  testsolution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: ['3.8.5']
        java: [ '8' ]
    steps:
      - name: Step - Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Step - Build with Maven
        run: mvn verify

      - name: Step - Create javadoc
        run: |
          javadoc -encoding utf8 -d javadoc -sourcepath src/main/java -subpackages minicp minicp
          mv -r javadoc /tmp/.
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Step - add new javadoc
        run: |
          cp -r /tmp/javadoc .
      - name: Step - Push changes to gh-page branch
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}

